### ISSUE TITLE
Upgrade to supported version of npm cli

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-validate#134]
Currently the `package-lock.json` file has `lockFileVersion` `1`: https://github.com/enketo/enketo-validate/blob/0cada72a2e8b3576edeabdc412243430775ee15b/package-lock.json#L4

The github action requires `npm` version 6: https://github.com/enketo/enketo-validate/blob/0cada72a2e8b3576edeabdc412243430775ee15b/.github/workflows/ci.yml#L26

`npm` v6 is no longer supported, as it is not bundled with any supported version of NodeJS:

> In the event of a security issue, the project will try to backport - when possible - security patches to versions of npm currently shipping with "[maintained](https://github.com/nodejs/Release#release-phases)" [Node.js versions](https://github.com/nodejs/LTS#lts-schedule1).
> -_https://github.com/npm/cli/wiki/Support-Policy#security-issues--backports_

**Comment by alxndrsn** [comment]
Trying to use NodeJS v16's bundled `npm` fails:

```
2023-07-12T06:14:20.9672586Z ##[group]Environment details
2023-07-12T06:14:21.5234671Z node: v16.20.1
2023-07-12T06:14:21.5262149Z npm: 8.19.4
2023-07-12T06:14:21.5262961Z yarn: 1.22.19
2023-07-12T06:14:21.5263765Z ##[endgroup]
2023-07-12T06:14:21.5431899Z ##[group]Run npm ci
2023-07-12T06:14:21.5432181Z [36;1mnpm ci[0m
2023-07-12T06:14:21.5491101Z shell: /usr/bin/bash -e {0}
2023-07-12T06:14:21.5491347Z env:
2023-07-12T06:14:21.5491602Z   NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
2023-07-12T06:14:21.5491929Z   NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
2023-07-12T06:14:21.5492187Z ##[endgroup]
2023-07-12T06:14:22.2650247Z npm WARN old lockfile 
2023-07-12T06:14:22.2651093Z npm WARN old lockfile The package-lock.json file was created with an old version of npm,
2023-07-12T06:14:22.2651655Z npm WARN old lockfile so supplemental metadata must be fetched from the registry.
2023-07-12T06:14:22.2652025Z npm WARN old lockfile 
2023-07-12T06:14:22.2652514Z npm WARN old lockfile This is a one-time fix-up, please be patient...
2023-07-12T06:14:22.2652840Z npm WARN old lockfile 
2023-07-12T06:14:23.4582887Z npm WARN old lockfile strip-ansi-cjs: No matching version found for strip-ansi-cjs@6.0.1.
2023-07-12T06:14:23.4584908Z npm WARN old lockfile     at module.exports (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
2023-07-12T06:14:23.4585748Z npm WARN old lockfile     at RegistryFetcher.manifest (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
2023-07-12T06:14:23.4590228Z npm WARN old lockfile     at async Array.<anonymous> (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:738:24)
2023-07-12T06:14:23.4592851Z npm WARN old lockfile  Could not fetch metadata for strip-ansi-cjs@6.0.1 strip-ansi-cjs: No matching version found for strip-ansi-cjs@6.0.1.
2023-07-12T06:14:23.4593854Z npm WARN old lockfile     at module.exports (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
2023-07-12T06:14:23.4595963Z npm WARN old lockfile     at RegistryFetcher.manifest (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
2023-07-12T06:14:23.4598271Z npm WARN old lockfile     at async Array.<anonymous> (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:738:24) {
2023-07-12T06:14:23.4600010Z npm WARN old lockfile   code: 'ETARGET',
2023-07-12T06:14:23.4601571Z npm WARN old lockfile   type: 'version',
2023-07-12T06:14:23.4603177Z npm WARN old lockfile   wanted: '6.0.1',
2023-07-12T06:14:23.4604858Z npm WARN old lockfile   versions: [ '1.0.0', '2.0.0', '8.0.0' ],
2023-07-12T06:14:23.4606547Z npm WARN old lockfile   distTags: { latest: '8.0.0' },
2023-07-12T06:14:23.4608228Z npm WARN old lockfile   defaultTag: 'latest'
2023-07-12T06:14:23.4609690Z npm WARN old lockfile }
2023-07-12T06:14:23.5640868Z npm WARN old lockfile string-width-cjs: No matching version found for string-width-cjs@4.2.3.
2023-07-12T06:14:23.5642355Z npm WARN old lockfile     at module.exports (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
2023-07-12T06:14:23.5645813Z npm WARN old lockfile     at RegistryFetcher.manifest (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
2023-07-12T06:14:23.5647243Z npm WARN old lockfile     at async Array.<anonymous> (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:738:24)
2023-07-12T06:14:23.5650961Z npm WARN old lockfile  Could not fetch metadata for string-width-cjs@4.2.3 string-width-cjs: No matching version found for string-width-cjs@4.2.3.
2023-07-12T06:14:23.5652745Z npm WARN old lockfile     at module.exports (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
2023-07-12T06:14:23.5654124Z npm WARN old lockfile     at RegistryFetcher.manifest (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
2023-07-12T06:14:23.5657410Z npm WARN old lockfile     at async Array.<anonymous> (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:738:24) {
2023-07-12T06:14:23.5658282Z npm WARN old lockfile   code: 'ETARGET',
2023-07-12T06:14:23.5658896Z npm WARN old lockfile   type: 'version',
2023-07-12T06:14:23.5659514Z npm WARN old lockfile   wanted: '4.2.3',
2023-07-12T06:14:23.5660374Z npm WARN old lockfile   versions: [ '1.0.0', '5.1.1' ],
2023-07-12T06:14:23.5661088Z npm WARN old lockfile   distTags: { latest: '5.1.1' },
2023-07-12T06:14:23.5661776Z npm WARN old lockfile   defaultTag: 'latest'
2023-07-12T06:14:23.5662275Z npm WARN old lockfile }
2023-07-12T06:14:23.7657542Z npm WARN old lockfile wrap-ansi-cjs: No matching version found for wrap-ansi-cjs@7.0.0.
2023-07-12T06:14:23.7658934Z npm WARN old lockfile     at module.exports (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
2023-07-12T06:14:23.7660045Z npm WARN old lockfile     at RegistryFetcher.manifest (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
2023-07-12T06:14:23.7661648Z npm WARN old lockfile     at async Array.<anonymous> (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:738:24)
2023-07-12T06:14:23.7662833Z npm WARN old lockfile  Could not fetch metadata for wrap-ansi-cjs@7.0.0 wrap-ansi-cjs: No matching version found for wrap-ansi-cjs@7.0.0.
2023-07-12T06:14:23.7664015Z npm WARN old lockfile     at module.exports (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
2023-07-12T06:14:23.7665078Z npm WARN old lockfile     at RegistryFetcher.manifest (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
2023-07-12T06:14:23.7666467Z npm WARN old lockfile     at async Array.<anonymous> (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:738:24) {
2023-07-12T06:14:23.7667277Z npm WARN old lockfile   code: 'ETARGET',
2023-07-12T06:14:23.7667910Z npm WARN old lockfile   type: 'version',
2023-07-12T06:14:23.7668740Z npm WARN old lockfile   wanted: '7.0.0',
2023-07-12T06:14:23.7669350Z npm WARN old lockfile   versions: [ '1.0.0', '8.0.0' ],
2023-07-12T06:14:23.7669943Z npm WARN old lockfile   distTags: { latest: '8.0.0' },
2023-07-12T06:14:23.7670582Z npm WARN old lockfile   defaultTag: 'latest'
2023-07-12T06:14:23.7671003Z npm WARN old lockfile }
2023-07-12T06:14:51.8790754Z npm WARN EBADENGINE Unsupported engine {
2023-07-12T06:14:51.8791895Z npm WARN EBADENGINE   package: 'enketo-core@7.2.4',
2023-07-12T06:14:51.8792734Z npm WARN EBADENGINE   required: { node: '>=14 <17', npm: '>=6 <7' },
2023-07-12T06:14:51.8793978Z npm WARN EBADENGINE   current: { node: 'v16.20.1', npm: '8.19.4' }
2023-07-12T06:14:51.8794394Z npm WARN EBADENGINE }
2023-07-12T06:14:51.8797807Z npm WARN EBADENGINE Unsupported engine {
2023-07-12T06:14:51.8798518Z npm WARN EBADENGINE   package: 'enketo-transformer@3.0.0',
2023-07-12T06:14:51.8799393Z npm WARN EBADENGINE   required: { node: '>=14 <17', npm: '>=6 <7' },
2023-07-12T06:14:51.8799936Z npm WARN EBADENGINE   current: { node: 'v16.20.1', npm: '8.19.4' }
2023-07-12T06:14:51.8800242Z npm WARN EBADENGINE }
2023-07-12T06:14:54.2964122Z npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
2023-07-12T06:14:54.4191430Z npm WARN deprecated rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
2023-07-12T06:14:55.1654027Z npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
2023-07-12T06:14:55.4604761Z npm WARN deprecated rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
2023-07-12T06:14:56.3421311Z npm WARN deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
2023-07-12T06:15:12.5195140Z npm ERR! code 1
2023-07-12T06:15:12.5199276Z npm ERR! path /home/runner/work/enketo-validate/enketo-validate/node_modules/libxslt
2023-07-12T06:15:12.5214501Z npm ERR! command failed
2023-07-12T06:15:12.5218222Z npm ERR! command sh -c -- node-gyp rebuild
2023-07-12T06:15:12.5225698Z npm ERR! make: Entering directory '/home/runner/work/enketo-validate/enketo-validate/node_modules/libxslt/build'
2023-07-12T06:15:12.5229157Z npm ERR! make: Leaving directory '/home/runner/work/enketo-validate/enketo-validate/node_modules/libxslt/build'
2023-07-12T06:15:12.5233275Z npm ERR! gyp info it worked if it ends with ok
2023-07-12T06:15:12.5236158Z npm ERR! gyp info using node-gyp@9.1.0
2023-07-12T06:15:12.5238944Z npm ERR! gyp info using node@16.20.1 | linux | x64
2023-07-12T06:15:12.5241794Z npm ERR! gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
2023-07-12T06:15:12.5244869Z npm ERR! gyp http GET https://nodejs.org/download/release/v16.20.1/node-v16.20.1-headers.tar.gz
2023-07-12T06:15:12.5245678Z npm ERR! gyp http 200 https://nodejs.org/download/release/v16.20.1/node-v16.20.1-headers.tar.gz
2023-07-12T06:15:12.5249502Z npm ERR! gyp http GET https://nodejs.org/download/release/v16.20.1/SHASUMS256.txt
2023-07-12T06:15:12.5252492Z npm ERR! gyp http 200 https://nodejs.org/download/release/v16.20.1/SHASUMS256.txt
2023-07-12T06:15:12.5255356Z npm ERR! gyp info spawn /usr/bin/python3
2023-07-12T06:15:12.5255736Z npm ERR! gyp info spawn args [
2023-07-12T06:15:12.5257863Z npm ERR! gyp info spawn args   '/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2023-07-12T06:15:12.5258407Z npm ERR! gyp info spawn args   'binding.gyp',
2023-07-12T06:15:12.5260003Z npm ERR! gyp info spawn args   '-f',
2023-07-12T06:15:12.5263876Z npm ERR! gyp info spawn args   'make',
2023-07-12T06:15:12.5264252Z npm ERR! gyp info spawn args   '-I',
2023-07-12T06:15:12.5266946Z npm ERR! gyp info spawn args   '/home/runner/work/enketo-validate/enketo-validate/node_modules/libxslt/build/config.gypi',
2023-07-12T06:15:12.5270164Z npm ERR! gyp info spawn args   '-I',
2023-07-12T06:15:12.5270848Z npm ERR! gyp info spawn args   '/home/runner/work/enketo-validate/enketo-validate/node_modules/libxslt/common.gypi',
2023-07-12T06:15:12.5273382Z npm ERR! gyp info spawn args   '-I',
2023-07-12T06:15:12.5275920Z npm ERR! gyp info spawn args   '/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2023-07-12T06:15:12.5278340Z npm ERR! gyp info spawn args   '-I',
2023-07-12T06:15:12.5278937Z npm ERR! gyp info spawn args   '/home/runner/.cache/node-gyp/16.20.1/include/node/common.gypi',
2023-07-12T06:15:12.5281058Z npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
2023-07-12T06:15:12.5281833Z npm ERR! gyp info spawn args   '-Dvisibility=default',
2023-07-12T06:15:12.5282629Z npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/runner/.cache/node-gyp/16.20.1',
2023-07-12T06:15:12.5283409Z npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/node-gyp',
2023-07-12T06:15:12.5284157Z npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/runner/.cache/node-gyp/16.20.1/<(target_arch)/node.lib',
2023-07-12T06:15:12.5284916Z npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/runner/work/enketo-validate/enketo-validate/node_modules/libxslt',
2023-07-12T06:15:12.5285767Z npm ERR! gyp info spawn args   '-Dnode_engine=v8',
2023-07-12T06:15:12.5286173Z npm ERR! gyp info spawn args   '--depth=.',
2023-07-12T06:15:12.5286598Z npm ERR! gyp info spawn args   '--no-parallel',
2023-07-12T06:15:12.5287061Z npm ERR! gyp info spawn args   '--generator-output',
2023-07-12T06:15:12.5290479Z npm ERR! gyp info spawn args   'build',
2023-07-12T06:15:12.5290918Z npm ERR! gyp info spawn args   '-Goutput_dir=.'
2023-07-12T06:15:12.5292483Z npm ERR! gyp info spawn args ]
2023-07-12T06:15:12.5293011Z npm ERR! gyp info spawn make
2023-07-12T06:15:12.5293742Z npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2023-07-12T06:15:12.5294579Z npm ERR! make: *** No rule to make target 'Release/obj.target/libexslt/deps/libxslt/libexslt/common.o', needed by 'Release/obj.target/deps/exslt.a'.  Stop.
2023-07-12T06:15:12.5295038Z npm ERR! gyp ERR! build error 
2023-07-12T06:15:12.5295452Z npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
2023-07-12T06:15:12.5297510Z npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
2023-07-12T06:15:12.5299250Z npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
2023-07-12T06:15:12.5299837Z npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
2023-07-12T06:15:12.5303547Z npm ERR! gyp ERR! System Linux 5.15.0-1041-azure
2023-07-12T06:15:12.5305661Z npm ERR! gyp ERR! command "/opt/hostedtoolcache/node/16.20.1/x64/bin/node" "/opt/hostedtoolcache/node/16.20.1/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2023-07-12T06:15:12.5307530Z npm ERR! gyp ERR! cwd /home/runner/work/enketo-validate/enketo-validate/node_modules/libxslt
2023-07-12T06:15:12.5330255Z npm ERR! gyp ERR! node -v v16.20.1
2023-07-12T06:15:12.5330780Z npm ERR! gyp ERR! node-gyp -v v9.1.0
2023-07-12T06:15:12.5331139Z npm ERR! gyp ERR! not ok
2023-07-12T06:15:12.5331380Z 
2023-07-12T06:15:12.5331655Z npm ERR! A complete log of this run can be found in:
2023-07-12T06:15:12.5332183Z npm ERR!     /home/runner/.npm/_logs/2023-07-12T06_14_21_823Z-debug-0.log
2023-07-12T06:15:12.5623795Z ##[error]Process completed with exit code 1.
2023-07-12T06:15:12.5701013Z Post job cleanup.
2023-07-12T06:15:12.6820493Z [command]/usr/bin/git version
2023-07-12T06:15:12.6876162Z git version 2.41.0
2023-07-12T06:15:12.6923001Z Temporarily overriding HOME='/home/runner/work/_temp/6f2e0cf5-9f64-49ad-9b7b-76ac6cea582b' before making global git config changes
2023-07-12T06:15:12.6923905Z Adding repository directory to the temporary git global config as a safe directory
2023-07-12T06:15:12.6930041Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/enketo-validate/enketo-validate
2023-07-12T06:15:12.6976532Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2023-07-12T06:15:12.7018101Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2023-07-12T06:15:12.7296346Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2023-07-12T06:15:12.7330187Z http.https://github.com/.extraheader
2023-07-12T06:15:12.7342946Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2023-07-12T06:15:12.7386796Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2023-07-12T06:15:12.7879070Z Cleaning up orphan processes
2023-07-12T06:15:12.8214593Z Terminate orphan process: pid (1839) (sh)
2023-07-12T06:15:12.8240080Z Terminate orphan process: pid (1846) (sh)
2023-07-12T06:15:12.8262365Z Terminate orphan process: pid (1847) (node-gyp)
2023-07-12T06:15:12.8285241Z Terminate orphan process: pid (1895) (make)
2023-07-12T06:15:12.8308540Z Terminate orphan process: pid (1904) (g++)
2023-07-12T06:15:12.8334704Z Terminate orphan process: pid (1905) (cc1plus)
```

- https://github.com/alxndrsn/enketo-validate/actions/runs/5528204510/jobs/10084740046

**Comment by MartijnR** [comment]
Thanks @alxndrsn! Switched to yarn (as the rest of Enketo has done) so we can use the latest versions of everything (though yarn instead of npm). 🥳
